# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.fi.scheduling
canonical: https://hl7.fi/fhir/finnish-scheduling
name: FinnishScheduling
title: Finnish Scheduling
description: Finnish HL7 FHIR implementation guide for scheduling, published and maintained by HL7 Finland
status: draft # draft | active | retired | unknown
version: 2.0.0-rc1
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ballot # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#FI "Finland" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Finland
  url: https://www.hl7.fi/
  email: mikael@sensotrend.com

dependencies:
  hl7.fhir.fi.base: latest

resources: 
  Appointment/605790:
    name: Appointment example 1
    description: Example appointment
  Appointment/appointment-status-extension-01:
    name: Appointment example 2, Waitlisted / Suunniteltu
  Appointment/appointment-status-extension-02:
    name: Appointment example 2, Proposed / Tilattu
  Appointment/appointment-status-extension-03:
    name: Appointment example 2, Pending / Ehdotettu
  Appointment/appointment-status-extension-04:
    name: Appointment example 2, Cancelled / Peruttu
  Appointment/appointment-status-extension-05:
    name: Appointment example 3, Proposed / Tilattu
  Appointment/appointment-status-extension-06:
    name: Appointment example 3, Booked / Varattu
  Appointment/appointment-status-extension-07:
    name: Appointment example 3, Arrived / Varattu
  Appointment/appointment-status-extension-08:
    name: Appointment example 3, Checked In / Ilmoittautunut
  Appointment/appointment-status-extension-09:
    name: Appointment example 3, Fulfilled / Alkanut
  Appointment/appointment-status-extension-10:
    name: Appointment example 3, Fulfilled / Toteutunut
  Appointment/example-appointment-4:
    name: Appointment example 4
    description: Example appointment
  HealthcareService/example-service-2:
    name: Isyyden selvittäminen
    description: Example healthcare service
  Organization/example-org-unit:
    name: Esimerkki-Palveluyksikkö
    description: Example organization unit
  Patient/patient-pentti:
    name: Pentti Potilas
    description: Example patient 2
  Patient/patient-petri:
    name: Petri Potilas
    description: Example patient 3
  Practitioner/practitioner-keijo:
    name: Keijo Kätilö
    description: Example practitioner 2
  Slot/123456789:
    name: Slot example

pages:
  index.md:
    title: Home
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  examples.md:
    title: Examples
  downloads.md:
    title: Downloads
  versions.md:
    title: Version History

parameters: 
  ipa-comparison: "{last}" # "{current}" | "{last}"

menu:
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Examples: examples.html
  Downloads: downloads.html
